### ISSUE TITLE
Error in Line 8

### ISSUE THREAD

**Issue by apmunch** [ricklupton/rmc#9]
Hi there. Running into the following error after executing:

`rmc -t markdown ffb3a170-cf8e-49f0-a4a9-ba4e8b52c840.rm`

Error is:

`Traceback (most recent call last):
  File "/home/parallels/.local/bin/rmc", line 8, in <module>
    sys.exit(cli())
TypeError: command.<locals>.decorator() missing 1 required positional argument: 'f'`

I'm running Ubuntu 20.04.2 LTS. As I'm running a VM on an M1 MacBook, it's ARM architecture (shouldn't matter, but figured I would mention it).

Thank you for the open source work!

**Comment by PascalNoisette** [comment]
Hi,

I also got the error with python 3.10, click 8.0.3 and rmc 0.1.1

It is related to https://github.com/pallets/click/issues/1359
`@click.command()` should have parentheses like any function call (in /usr/local/lib/python3.10/dist-packages/rmc/cli.py).

Regards,
Pascal Noisette

**Comment by ImpaleAskewArdently** [comment]
I was able to fix this by running `pip install click --upgrade`

The issue was caused by having an outdated version of click (it worked with version 8.1.8).
